csschallenge
Code-the-Stars/illuminate pull request #18
Opened 2024-06-01 11:31 UTC by OmegaOrbitals

my entry for the hackathon

2024-06-01 16:18 UTC, Lightshayan commented
Hey Omega! Can you host your website onto Github Sites or Vercel?

2024-06-02 14:29 UTC, OmegaOrbitals commented
> Hey Omega! Can you host your website onto Github Sites or Vercel? 

Do I include the entire site, or just my folder in csschallenge?

2024-06-02 14:32 UTC, Lightshayan commented
Just your website, not the whole thing.

2024-06-02 17:01 UTC, Lightshayan requested changes
Please host your website on either Vercel or Github Pages so we can preview it. Thank you!

2024-06-12 08:15 UTC, OmegaOrbitals commented
> Please host your website on either Vercel or Github Pages so we can preview it. Thank you!

Hi, can I use Glitch? Idk how to use Vercel or Pages.

2025-06-17 10:12 UTC, closed without merging